apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}-{{ .Values.version }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Values.version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http  
    port: {{ .Values.service.servicePort }}
  selector:
    app: "{{  .Chart.Name }}-{{ .Values.version }}-selector"
